name: chili_flutter_analysis
description: Lint rules for Chili Flutter projects
version: 1.1.2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # Static code analysis
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.5
  lints: ^2.0.1
  test: ^1.24.1
