name: chili_flutter_analysis
description: Lint rules for Chili Flutter projects
version: 1.2.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # Static code analysis
  flutter_lints: ^3.0.1
  lints: ^3.0.0
